# -*- coding: utf-8 -*-
"""Aula2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vvG1yDOiOKQdmUjEwG-nEwYxLNEkYp2Q
"""

#Conversão de temperatura com condicional e controle de fluxo

print('Insira a medida de conversão desejada em metros: \n1: C -> F \n2: F -> C \n3: C -> K \n4: K -> C \n5: F -> K \n6: K -> F')
escolha = input('Insira a medida de conversão desejada: ')

if   escolha =='1':
     temperatura = input('Insira a temperatura em graus Celsius para serem convertidos em Fahrenhelt:')
     temperatura = eval(temperatura)
     temp = temperatura*1.8 + 32
     print(temp)
elif escolha == '2':
     temperatura = input('Insira a temperatura em graus Fahrenheit para serem convertidos para Celsius:')
     temperatura = eval(temperatura)
     temp = (temperatura - 32)/1.8
     print(temp)
elif escolha == '3':
     temperatura = input('Insira a temperatura em Celsius para serem convertidos em kelvin:')
     temperatura = eval(temperatura)
     temp = temperatura + 273.15
     print(temp)
elif escolha == '4':
     temperatura = input('Insira a temperatura graus Kelvin para serem convertidos em Celsius:')
     temperatura = eval(temperatura)
     temp = (temperatura - 273.15)
     print(temp)
elif escolha == '5':
     temperatura = input('Insira a temperatura em graus Fahreit para serem convertidos em Kelvin:')
     temperatura = eval(temperatura)
     temp = (temperatura*1.8 - 459.67)
     print(temp)
elif escolha == '6':
     temperatura = input('Insira a temperatura em Graus Kelvin para serem convertidos para Fahrenheit:')
     temperatura = eval(temperatura)
     temp = (temperatura + 459.67)/1.8
     print(temp)
else:
     print('Opção invalida')
exit ()

#Desafio 2 - conversão de unidades de medida
print('Insira a unidade do valor de entrada:')
#unidadeconversão_1 = input('\n Pol para polegadas \n Pé para pés \n J para jarda \n M para milha e \n L para légua:')
unidadeconversão_1 = input('\n Pol para polegadas \n Pé para pés \n:')
print('\n Insira o valor que se deseja converter:')
valorconversão = input('\n Valor:')
print('\n Para qual unidade se deseja a conversão')
unidadeconversão_2 = input('\n Pol para polegadas \n Pé para pés:')

if unidadeconversão_1 == 'Pol' and unidadeconversão_2 == 'Pé':
   valorconversão = eval(valorconversão)
   calc = valorconversão / 12
   print('Resultado: \n', calc)
elif unidadeconversão_1 == 'Pé' and unidadeconversão_2 == 'Pol':
     valorconversão = eval(valorconversão)
     calc = 12/valorconversão
     print('Resultado: \n', calc)
print('Finalizado com sucesso')P

#Desafio 2 - conversão de unidades de medida
print('Selecione as unidades de conversão: \n1- Pol para M \n2- Pé para M \n3- Jarda para M \n4- Milha para M \n5- Légua para M')
conversão = input('')


if conversão== '1':
   valorconversão = input('insira o valor:')
   valorconversão = eval(valorconversão)
   resultado = valorconversão*0.0254
   print(resultado)

elif conversão== '2':
   valorconversão = input('insira o valor:')
   valorconversão = eval(valorconversão)
   resultado = valorconversão*0.3048
   print(resultado)

elif conversão== '3':
   valorconversão = input('insira o valor:')
   valorconversão = eval(valorconversão)
   resultado = valorconversão*0.91
   print(resultado)

elif conversão== '4':
   valorconversão = input('insira o valor:')
   valorconversão = eval(valorconversão)
   resultado = valorconversão*1609.34
   print(resultado)

elif conversão== '5':
   valorconversão = input('insira o valor:')
   valorconversão = eval(valorconversão)
   resultado = valorconversão*4828.032
   print(resultado)

   print('Cálculo finalizado')



import random

estrofes = ['Andá com fé eu vou \nQue a fé não costuma faiá \nAndá com fé eu vou \nQue a fé não costuma faiá \nAndá com fé eu vou \nQue a fé não costuma faiá',
            'Que a fé tá na mulher \nA fé tá na cobra coral \nOh oh \nNum pedaço de pão',
            'A fé tá na maré \nNa lâmina de um punhal \nOh oh \nNa luz, na escuridão \nAndá com fé eu vou \nQue a fé não costuma faiá olêlê \nAndá com fé eu vou \nQue a fé não costuma faiá \nOlálá',
            'Andá com fé eu vou \nQue a fé não costuma faiá \nOh menina \nAndá com fé eu vou \nQue a fé não costuma faiá']
x = random.randrange(0, len(estrofes))
musica_final = ''
while x > 0:
  x = random.randrange(0, len(estrofes))
  n = random.randrange(0, len(estrofes))
  musica_final += estrofes[n]+'\n\n'
print(musica_final)

n = 0

while n!= 25:
  n += 1
  print(n)

#Desafio 3import random
n = 0

while n!= 10:
  n = random.randrange(0,11)
  print(n)

#Desafio 4 - função imputar duas notas e se o aluno tiver média superior a 8 ele pode ir para o intercambio
def aprovado():
    nota_1 = input('Inserir a 1 nota \n')
    nota_1 = eval(nota_1)
    nota_2 = input('Inserir a 2 nota \n')
    nota_2 = eval(nota_2)
    calc = (nota_1 + nota_2)/2
    if calc >=8:
     print('Aprovado para o itercambio')
    else:
     print('Reprovado para o intercambio')

aprovado()



A = {'ANA', 'MARIA', 'LAURA', 'ROSA'}

type(A)

B= {'MARIO', 'PEDRO', 'ROSA', 'LAURA', 'MARIA'}

A.union (B)

A.intersection(B)

A.difference(B)

tabela_mercado = {'Produto': ['banana', 'abaicaxi','mamao', 'pera', 'uva', 'maca'],
                  'Preço': [1.5, 10, 8, 7, 3, 5],
                  'Estoque':[ 1000, 500, 700, 30, 10000, 800]}

tabela_mercado.

#Desafio para fazer um sistema de laços
def cadastro():
    import pandas as pd
    import numpy as np
  ##Carregar BD no computador


    ##Declaração das listas de armazenamento dos dados
    list_a = []
    list_b = []
    list_c = []
    list_d = []

  ##While para a inserção dos cadastros multiplos
    q = 'Sim'
  
    while q == 'Sim':
        ##Etapa de inserção de dados
        a = input('insira o código do produto: ')
        b = input('insira o nome do produto: ')
        c = input('insira a quantidade em estoque: ')
        d = input ('insira o preço do produto: ')
        c = eval(c)

        ##Inserção dos dados
        list_a.append(a)
        list_b.append(b)
        list_c.append(c)
        list_d.append(d)

        q = input('Deseja incluir um novo produto? Sim e Nao: ')

  #dar append nas listas vazias com o BD do computador


  ##Criação do BD na forma de um dict
      
        BD_dict = {'Codigo' : list_a,
                 'Produto' : list_b,
                 'Quantidade' : list_c,
                 'Preço' : list_d}

    ##Salvar BD no computador 
    pd.DataFrame(DB_dict)
                       
                           
    to_csv('BD_dict.csv')

    #retornar BD na tela
    return(BD_dict)

cadastro()

import numpy as np

A = np.array([1,2,3,4])

data1 = np.random.randn(2,3)

data2 = np.random.randn(2,3)

type(data)

#Tipo de matriz que estou manipulando
data.shape

data1

data2

data1 + data2

#Multiplicação da matriz por um valor constante
data1*10

#saber o tipo de elementos que estão dentro da matriz
data1.dtype

c = np.array([[1,2,3],[4,5,6],[7,8,9]])
c

#Criar matriz nula no numpy
np.zeros((3,3))

np.empty((3,3))

np.empty((3,3,3))